# Regenerates LefthyTools/Data/FlightPaths.lua: the length of every flight path in WoW: Forever.
#
# Source: wago.tools exports of the client's TaxiPath (one row per direct path between two flight
# points) and TaxiPathNode (its waypoints) tables. A path's length is the sum of the straight
# segments between its waypoints (3D, in yards; a change of continent is a jump, not flown); its
# delay is the sum of the waypoints' Delay (seconds the flight waits there). Cinematic flights
# (Modules/Tweaks/Flight.lua) add up the legs of a flight and divide by the flight speed for the
# time left.
# Run it when Forever gets new builds:
#   .\tools\update-flight-paths.ps1                       the latest Forever build
#   .\tools\update-flight-paths.ps1 -ForeverBuild 1.60.1.70205
param(
	[string]$ForeverBuild
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor 3072

if (-not $ForeverBuild) {
	$builds = Invoke-RestMethod 'https://wago.tools/api/builds' -TimeoutSec 60
	$all = $builds.PSObject.Properties | ForEach-Object { $_.Value } | ForEach-Object { $_ }
	# WoW: Forever is version 1.60.x (listed under a beta product on wago.tools).
	$ForeverBuild = ($all | Where-Object { $_.version -like '1.60.*' } |
		Sort-Object { [version]$_.version } -Descending | Select-Object -First 1).version
}
if (-not $ForeverBuild) { throw 'Could not determine the Forever build; pass -ForeverBuild.' }

function Get-Table([string]$name) {
	$response = Invoke-WebRequest "https://wago.tools/db2/$name/csv?build=$ForeverBuild" -UseBasicParsing -TimeoutSec 120
	$rows = $response.Content | ConvertFrom-Csv
	if (@($rows).Count -lt 10) { throw "$name for $ForeverBuild looks incomplete ($(@($rows).Count) rows)." }
	return $rows
}

Write-Host "WoW: Forever $ForeverBuild"
$paths = Get-Table 'TaxiPath'
$waypoints = Get-Table 'TaxiPathNode'
$byPath = @{}
foreach ($w in $waypoints) {
	$id = [int]$w.PathID
	if (-not $byPath.ContainsKey($id)) { $byPath[$id] = New-Object System.Collections.Generic.List[object] }
	$byPath[$id].Add($w)
}

$inv = [Globalization.CultureInfo]::InvariantCulture
$lines = New-Object System.Collections.Generic.List[string]
$count = 0
foreach ($p in ($paths | Sort-Object { [int]$_.FromTaxiNode }, { [int]$_.ToTaxiNode })) {
	if ([int]$p.FromTaxiNode -eq 0 -or [int]$p.ToTaxiNode -eq 0) { continue } # not between two flight points
	$list = $byPath[[int]$p.ID]
	if (-not $list) { continue }
	$list = $list | Sort-Object { [int]$_.NodeIndex }
	$length, $delay, $prev = 0.0, 0, $null
	foreach ($w in $list) {
		$delay += [int]$w.Delay
		if ($prev -and $prev.ContinentID -eq $w.ContinentID) {
			$dx = [double]::Parse($w.Loc_0, $inv) - [double]::Parse($prev.Loc_0, $inv)
			$dy = [double]::Parse($w.Loc_1, $inv) - [double]::Parse($prev.Loc_1, $inv)
			$dz = [double]::Parse($w.Loc_2, $inv) - [double]::Parse($prev.Loc_2, $inv)
			$length += [Math]::Sqrt($dx * $dx + $dy * $dy + $dz * $dz)
		}
		$prev = $w
	}
	$lines.Add("`t[`"$($p.FromTaxiNode)>$($p.ToTaxiNode)`"] = { $([Math]::Round($length)), $delay },")
	$count++
}

$out = New-Object System.Collections.Generic.List[string]
$out.Add('local _, ns = ...')
$out.Add('')
$out.Add('-- Every flight path: ["<from node>><to node>"] = { yards flown, seconds waited on the way }.')
$out.Add("-- Generated by tools/update-flight-paths.ps1 from wago.tools TaxiPath and TaxiPathNode exports")
$out.Add("-- of WoW: Forever $ForeverBuild. $count paths. Node IDs are C_TaxiMap's nodeID.")
$out.Add('ns.FLIGHT_PATHS = {')
foreach ($l in $lines) { $out.Add($l) }
$out.Add('}')

$target = Join-Path (Split-Path $PSScriptRoot) 'LefthyTools\Data\FlightPaths.lua'
[IO.File]::WriteAllLines($target, [string[]]$out, (New-Object Text.UTF8Encoding $false))
Write-Host "$count flight paths written to $target"
