# Regenerates LefthyTools/Data/ForeverQuests.lua: the quests that are new in WoW: Forever.
#
# Source: wago.tools exports of the clients' QuestV2 table (one row per quest that owns a
# completion bit). Two lists:
#   new in Forever: in Forever's table, not in Classic Era's, and ID >= 86000 (the few lower IDs
#     missing from Era's table are original Classic quests, e.g. 3382, 8193, 8249);
#   later Classic: in both tables with ID >= 10000. Original Classic's quests all have IDs below
#     10000; Classic Era's client also carries the content added since (Season of Discovery,
#     Hardcore, Anniversary: IDs from 55000 on), which Forever's client has too. Players never saw
#     those in original Classic, so they get the marker as well.
# Run it when Forever gets new builds:
#   .\tools\update-forever-quests.ps1                         latest Forever and Era builds
#   .\tools\update-forever-quests.ps1 -ForeverBuild 1.60.1.70170 -EraBuild 1.15.9.70003
param(
	[string]$ForeverBuild,
	[string]$EraBuild
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor 3072
$MinId = 86000
$OriginalMaxId = 9999 # original Classic's quest IDs are all below this

if (-not $ForeverBuild -or -not $EraBuild) {
	$builds = Invoke-RestMethod 'https://wago.tools/api/builds' -TimeoutSec 60
	$all = $builds.PSObject.Properties | ForEach-Object { $_.Value } | ForEach-Object { $_ }
	if (-not $ForeverBuild) {
		# WoW: Forever is version 1.60.x (listed under a beta product on wago.tools).
		$ForeverBuild = ($all | Where-Object { $_.version -like '1.60.*' } |
			Sort-Object { [version]$_.version } -Descending | Select-Object -First 1).version
	}
	if (-not $EraBuild) {
		$EraBuild = ($builds.wow_classic_era | Sort-Object { [version]$_.version } -Descending | Select-Object -First 1).version
	}
}
if (-not $ForeverBuild -or -not $EraBuild) { throw 'Could not determine the builds; pass -ForeverBuild and -EraBuild.' }

function Get-QuestIds([string]$build) {
	$response = Invoke-WebRequest "https://wago.tools/db2/QuestV2/csv?build=$build" -UseBasicParsing -TimeoutSec 120
	$ids = $response.Content | ConvertFrom-Csv | ForEach-Object { [int]$_.ID }
	if (@($ids).Count -lt 1000) { throw "QuestV2 for $build looks incomplete ($(@($ids).Count) rows)." }
	return $ids
}

Write-Host "Forever $ForeverBuild vs Classic Era $EraBuild"
$era = @{}
foreach ($id in Get-QuestIds $EraBuild) { $era[$id] = $true }
$forever = Get-QuestIds $ForeverBuild | Sort-Object -Unique
$new = $forever | Where-Object { $_ -ge $MinId -and -not $era.ContainsKey($_) }
$later = $forever | Where-Object { $_ -gt $OriginalMaxId -and $era.ContainsKey($_) }

# IDs as "86574-86580,86590,..." in string pieces of at most ~90 characters.
function Format-Ranges($ids) {
	$parts = New-Object System.Collections.Generic.List[string]
	$start = $null; $prev = $null
	foreach ($id in $ids) {
		if ($null -ne $prev -and $id -eq $prev + 1) { $prev = $id; continue }
		if ($null -ne $start) { $parts.Add($(if ($start -eq $prev) { "$start" } else { "$start-$prev" })) }
		$start = $id; $prev = $id
	}
	if ($null -ne $start) { $parts.Add($(if ($start -eq $prev) { "$start" } else { "$start-$prev" })) }
	$lines = New-Object System.Collections.Generic.List[string]
	$line = ''
	foreach ($part in $parts) {
		if ($line.Length + $part.Length -gt 90) { $lines.Add($line); $line = '' }
		$line += $part + ','
	}
	if ($line) { $lines.Add($line) }
	return $lines
}

$out = New-Object System.Collections.Generic.List[string]
$out.Add('local _, ns = ...')
$out.Add('')
$out.Add('-- Quests players never saw in original Classic. Generated by tools/update-forever-quests.ps1')
$out.Add("-- from wago.tools QuestV2 exports: WoW: Forever $ForeverBuild vs Classic Era $EraBuild.")
$out.Add('-- Comma-separated IDs and ID ranges ("first-last").')
$out.Add('')
$out.Add("-- New in WoW: Forever: in Forever's table, not in Classic Era's, ID >= $MinId. $(@($new).Count) quests.")
$out.Add('ns.FOREVER_QUEST_IDS = table.concat({')
foreach ($l in (Format-Ranges $new)) { $out.Add("`t`"$l`",") }
$out.Add('})')
$out.Add('')
$out.Add("-- Later Classic content (Season of Discovery, Hardcore, Anniversary) that Forever's client")
$out.Add("-- has too: in both tables, ID > $OriginalMaxId. $(@($later).Count) quests.")
$out.Add('ns.LATER_CLASSIC_QUEST_IDS = table.concat({')
foreach ($l in (Format-Ranges $later)) { $out.Add("`t`"$l`",") }
$out.Add('})')

$target = Join-Path (Split-Path $PSScriptRoot) 'LefthyTools\Data\ForeverQuests.lua'
New-Item -ItemType Directory -Force (Split-Path $target) | Out-Null
[IO.File]::WriteAllLines($target, [string[]]$out, (New-Object Text.UTF8Encoding $false))
Write-Host "$(@($new).Count) new in Forever and $(@($later).Count) from later Classic written to $target"
