# Regenerates LefthyTools/Data/ForeverQuests.lua: the quests that are new in WoW: Forever.
#
# Source: wago.tools exports of the clients' QuestV2 table (one row per quest that owns a
# completion bit). New = in Forever's table, not in Classic Era's, and ID >= 86000: the few
# lower IDs missing from Era's table are original Classic quests (e.g. 3382, 8193, 8249).
# Run it when Forever gets new builds:
#   .\tools\update-forever-quests.ps1                         latest Forever and Era builds
#   .\tools\update-forever-quests.ps1 -ForeverBuild 1.60.1.70170 -EraBuild 1.15.9.70003
param(
	[string]$ForeverBuild,
	[string]$EraBuild
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor 3072
$MinId = 86000

if (-not $ForeverBuild -or -not $EraBuild) {
	$builds = Invoke-RestMethod 'https://wago.tools/api/builds' -TimeoutSec 60
	$all = $builds.PSObject.Properties | ForEach-Object { $_.Value } | ForEach-Object { $_ }
	if (-not $ForeverBuild) {
		# WoW: Forever is version 1.60.x (listed under a beta product on wago.tools).
		$ForeverBuild = ($all | Where-Object { $_.version -like '1.60.*' } |
			Sort-Object { [version]$_.version } -Descending | Select-Object -First 1).version
	}
	if (-not $EraBuild) {
		$EraBuild = ($builds.wow_classic_era | Sort-Object { [version]$_.version } -Descending | Select-Object -First 1).version
	}
}
if (-not $ForeverBuild -or -not $EraBuild) { throw 'Could not determine the builds; pass -ForeverBuild and -EraBuild.' }

function Get-QuestIds([string]$build) {
	$response = Invoke-WebRequest "https://wago.tools/db2/QuestV2/csv?build=$build" -UseBasicParsing -TimeoutSec 120
	$ids = $response.Content | ConvertFrom-Csv | ForEach-Object { [int]$_.ID }
	if (@($ids).Count -lt 1000) { throw "QuestV2 for $build looks incomplete ($(@($ids).Count) rows)." }
	return $ids
}

Write-Host "Forever $ForeverBuild vs Classic Era $EraBuild"
$era = @{}
foreach ($id in Get-QuestIds $EraBuild) { $era[$id] = $true }
$new = Get-QuestIds $ForeverBuild | Where-Object { $_ -ge $MinId -and -not $era.ContainsKey($_) } | Sort-Object -Unique

# Consecutive IDs as ranges: "86574-86580,86590,..."
$parts = New-Object System.Collections.Generic.List[string]
$start = $null; $prev = $null
foreach ($id in $new) {
	if ($null -ne $prev -and $id -eq $prev + 1) { $prev = $id; continue }
	if ($null -ne $start) { $parts.Add($(if ($start -eq $prev) { "$start" } else { "$start-$prev" })) }
	$start = $id; $prev = $id
}
if ($null -ne $start) { $parts.Add($(if ($start -eq $prev) { "$start" } else { "$start-$prev" })) }

# Wrapped into several string pieces so no line gets too long.
$lines = New-Object System.Collections.Generic.List[string]
$line = ''
foreach ($part in $parts) {
	if ($line.Length + $part.Length -gt 90) { $lines.Add($line); $line = '' }
	$line += $part + ','
}
if ($line) { $lines.Add($line) }

$out = New-Object System.Collections.Generic.List[string]
$out.Add('local _, ns = ...')
$out.Add('')
$out.Add('-- Quests that are new in WoW: Forever. Generated by tools/update-forever-quests.ps1 from')
$out.Add("-- wago.tools QuestV2 exports: WoW: Forever $ForeverBuild vs Classic Era $EraBuild.")
$out.Add("-- Rule: in Forever's table, not in Classic Era's, quest ID >= $MinId. $(@($new).Count) quests.")
$out.Add('-- Comma-separated IDs and ID ranges ("first-last").')
$out.Add('ns.FOREVER_QUEST_IDS = table.concat({')
foreach ($l in $lines) { $out.Add("`t`"$l`",") }
$out.Add('})')

$target = Join-Path (Split-Path $PSScriptRoot) 'LefthyTools\Data\ForeverQuests.lua'
New-Item -ItemType Directory -Force (Split-Path $target) | Out-Null
[IO.File]::WriteAllLines($target, [string[]]$out, (New-Object Text.UTF8Encoding $false))
Write-Host "$(@($new).Count) new quests in $($parts.Count) ranges written to $target"
